apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-apps
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/media-service
  newName: ghcr.io/arda-labs/media-service
  newTag: 7ee4d875353be345f8a510a9ceb445819f2398a2
