apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-apps
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/media-service
  newName: ghcr.io/arda-labs/media-service
  newTag: a7c8b20
