apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-apps
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/notification-service
  newName: ghcr.io/arda-labs/notification-service
  newTag: latest
patches:
- path: route-dev-hosts.patch.yaml
  target:
    group: apisix.apache.org
    kind: ApisixRoute
    name: notification-service-v1-route
    version: v2
