apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: arda-platform
  namespace: argocd
spec:
  description: Platform project for the clean Arda rebuild
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: gateway
    server: https://kubernetes.default.svc
  - namespace: identity
    server: https://kubernetes.default.svc
  - namespace: infra
    server: https://kubernetes.default.svc
  - namespace: arda-prod
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/arda-labs/arda-infra.git
  - https://charts.zitadel.com
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
