apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  namespace: infra
spec:
  ports:
    - port: 9333
      targetPort: 9333
      name: master
  selector:
    app: seaweedfs-master
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-s3
  namespace: infra
spec:
  ports:
    - port: 8333
      targetPort: 8333
      name: s3
  selector:
    app: seaweedfs-s3
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-filer
  namespace: infra
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: http
    - port: 18888
      targetPort: 18888
      name: grpc
  selector:
    app: seaweedfs-filer

