apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-volume
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs-volume
  template:
    metadata:
      labels:
        app: seaweedfs-volume
    spec:
      containers:
        - name: volume
          image: chrislusf/seaweedfs:latest
          args:
            - "volume"
            - "-master=seaweedfs-master.infra.svc.cluster.local:9333"
            - "-port=8080"
            - "-ip=$(POD_IP)"
            - "-ip.bind=0.0.0.0"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8080
            - containerPort: 18080
            - containerPort: 8333
