apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-dev
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/iam-service
  newName: ghcr.io/arda-labs/iam-service
  newTag: da47cf4
configMapGenerator:
- behavior: merge
  literals:
  - REDIS_ADDR=thinkcenter:6379
  name: iam-service-config
