apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redpanda
  namespace: argocd
spec:
  project: default
  source:
    chart: redpanda
    repoURL: https://charts.redpanda.com
    targetRevision: 5.x.x
    helm:
      values: |
        storage:
          persistentVolume:
            enabled: true
            size: 10Gi
        resources:
          cpu:
            cores: 1
          memory:
            limit: 2Gi
        external:
          enabled: false
        monitoring:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
