apiVersion: batch/v1
kind: Job
metadata:
  name: redpanda-create-topics
  namespace: arda-apps
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: rpk
          image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
          command:
            - sh
            - -c
            - |
              rpk topic create arda.notification.events.v1 \
                --brokers redpanda.arda-apps.svc.cluster.local:9092 \
                --partitions 3 \
                --replicas 1 || true
