apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-dev
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/mfe-shell
  newName: ghcr.io/arda-labs/mfe-shell
  newTag: fa521c3
configMapGenerator:
- behavior: merge
  literals:
  - API_URL=https://arda.io.vn
  name: mfe-shell-env-config
