apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-dev
resources:
  - ../../base
images:
  - name: ghcr.io/arda-labs/mfe-shell
    newName: ghcr.io/arda-labs/mfe-shell
    newTag: 881c8d3
configMapGenerator:
  - behavior: merge
    literals:
      - API_URL=https://arda.io.vn/api
      - MFE_IAM_URL=https://arda.io.vn/mfe-iam
      - MFE_COMMON_URL=https://arda.io.vn/mfe-common
    name: mfe-shell-env-config
