apiVersion: v1
kind: ConfigMap
metadata:
  name: mfe-iam-env-config
data:
  env.template.js: |
    (function(window) {
      window.__env = window.__env || {};
      window.__env.apiUrl = "${API_URL}";
      window.__env.authAuthority = "${AUTH_AUTHORITY}";
      window.__env.authClientId = "${AUTH_CLIENT_ID}";
    })(this);
