apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: zitadel-route
spec:
  http:
  - name: zitadel-auth
    priority: 100
    match:
      hosts:
      - auth.arda.io.vn
      paths:
      - /*
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "auth.arda.io.vn"
    backends:
    - serviceName: zitadel.arda-dev.svc.cluster.local  # Do Zitadel nằm ở namespace khác nên cần FQDN
      servicePort: 8080
