apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: zitadel-route
spec:
  http:
  - name: zitadel-auth
    priority: 100
    match:
      hosts:
      - auth.arda.io.vn
      paths:
      - /*
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "https://arda.io.vn"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since"
        max_age: 3600
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: "auth.arda.io.vn"
    backends:
    - serviceName: zitadel.arda-dev.svc.cluster.local  # Do Zitadel nằm ở namespace khác nên cần FQDN
      servicePort: 8080
