gateway:
  type: ClusterIP

etcd:
  enabled: true
  persistence:
    enabled: false

ingress-controller:
  enabled: true
  config:
    apisix:
      adminAPIVersion: v3
  initSyncDelay: 0s
  # Đảm bảo Controller có quyền đọc CRD từ Kubernetes
  rbac:
    create: true

dashboard:
  enabled: false
