service:
  type: NodePort

apisix:
  deployment:
    admin:
      enable_admin_ui: true
      type: ClusterIP

etcd:
  enabled: true
  persistence:
    enabled: false

ingress-controller:
  enabled: true
  apisix:
    adminService:
      namespace: gateway
      name: apisix-admin
      port: 9180
  gatewayProxy:
    createDefault: true
  config:
    provider:
      initSyncDelay: 0s
    apisix:
      adminAPIVersion: v3
    kubernetes:
      # Watch all namespaces
      namespaceSelector:
        - ""
      watchEndpointslices: false
  # Đảm bảo Controller có quyền đọc CRD từ Kubernetes
  rbac:
    create: true
