apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apisix
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/gateway/apisix/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/ingress/cloudflared/overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-shell-dev
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-shell/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-common-dev
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-common/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/services/zitadel/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-crm-dev
  namespace: argocd
spec:
  project: arda-dev
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/services/crm/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
