apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/notification-service/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mdm-service
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mdm-service/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam-service
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/iam-service/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-shell
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-shell/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-iam
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-iam/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-ntf
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-ntf/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mfe-mdm
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/mfe-mdm/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: arda-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
