apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-routes
  namespace: argocd
spec:
  project: arda-platform
  source:
    repoURL: https://github.com/arda-labs/arda-infra.git
    targetRevision: main
    path: apps/identity/zitadel/base
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
