apiVersion: v1
kind: ConfigMap
metadata:
  name: mdm-service-config
data:
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 10s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 10s

    data:
      database:
        driver: postgres
        source: "${DATABASE_URL}"
      redis:
        addr: "${REDIS_ADDR}"
        read_timeout: 0.2s
        write_timeout: 0.2s

    jwt:
      jwks_endpoint: "https://arda.io.vn/oauth/v2/keys"
      issuer: "https://arda.io.vn"
      audience: "370596460112183382"
