apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-apps
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/mfe-mdm
  newName: ghcr.io/arda-labs/mfe-mdm
  newTag: 80d9327
patches:
- path: route-dev-local.patch.yaml
  target:
    group: apisix.apache.org
    kind: ApisixRoute
    name: mfe-mdm-route
    version: v2
