apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfe-ntf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfe-ntf
  template:
    metadata:
      labels:
        app: mfe-ntf
    spec:
      containers:
      - name: mfe-ntf
        image: ghcr.io/arda-labs/mfe-ntf:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mfe-ntf
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: mfe-ntf
