apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-dev
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/mfe-common
  newName: ghcr.io/arda-labs/mfe-common
  newTag: 1018fe9
