apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arda-apps
resources:
- ../../base
images:
- name: ghcr.io/arda-labs/mfe-common
  newName: ghcr.io/arda-labs/mfe-common
  newTag: ba3bc99
patches:
- path: route-dev-local.patch.yaml
  target:
    group: apisix.apache.org
    kind: ApisixRoute
    name: mfe-common-route
    version: v2
