apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-service
  template:
    metadata:
      labels:
        app: crm-service
    spec:
      containers:
        - name: crm-service
          image: ghcr.io/arda-labs/crm-service:latest
          env:
            - name: ZEEBE_CLIENT_BROKER_GATEWAY-ADDRESS
              value: 'camunda8-zeebe.infra.svc.cluster.local:26500'
            - name: SPRING_R2DBC_URL
              value: 'r2dbc:postgresql://postgres-external.infra.svc.cluster.local:5432/crm'
            - name: SPRING_R2DBC_USERNAME
              value: 'postgres'
            - name: SPRING_R2DBC_PASSWORD
              value: 'postgres'
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crm-service
spec:
  selector:
    app: crm-service
  ports:
    - port: 80
      targetPort: 8080
