apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: mfe-shell-route
spec:
  http:
    - name: mfe-shell
      priority: 1
      match:
        hosts:
          - arda.io.vn
        paths:
          - /*
        exprs:
          - subject:
              scope: Variable
              name: uri
            op: NotRegexMatch
            value: "^/(api|mfe-iam|mfe-common)/.*"
      plugins:
        - name: cors
          enable: true
          config:
            allow_origins: "https://arda.io.vn"
            allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
            allow_headers: "content-type,authorization,x-tenant-id"
            expose_headers: "content-length,x-tenant-id"
            allow_credential: true
            max_age: 3600
      backends:
        - serviceName: mfe-shell
          servicePort: 80
