apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: iam-service-route
spec:
  http:
  # Route Login Public (Không qua plugin auth)
  - name: iam-login-public
    priority: 10
    match:
      hosts:
      - api.arda.io.vn
      paths:
      - /v1/auth/login
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "https://arda.io.vn"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "*"
        expose_headers: "*"
        allow_credential: true
        max_age: 3600
    backends:
    - serviceName: iam-service
      servicePort: 80

  # Route API - qua Forward Auth
  - name: iam-api
    priority: 9
    match:
      hosts:
      - api.arda.io.vn
      paths:
      - /v1/*
    plugins:
    - name: cors
      enable: true
      config:
        allow_origins: "https://arda.io.vn"
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "content-type,authorization,x-tenant-id"
        expose_headers: "content-length,x-tenant-id"
        allow_credential: true
        max_age: 3600
    - name: forward-auth
      enable: true
      config:
        uri: "http://iam-service.arda-dev.svc.cluster.local:80/v1/auth/forward"
        request_headers:
          - Authorization
        upstream_headers:
          - X-User-Id
          - X-Tenant-Id
    backends:
    - serviceName: iam-service
      servicePort: 80
